<a href="https://colab.research.google.com/github/SkyJoyTianle/leetcode/blob/main/819%E6%9C%80%E5%B8%B8%E8%A7%81%E5%8D%95%E8%AF%8D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

a = torch.ones(2,3,2)
b = torch.ones(2,3,2)
c = torch.cat((a,b),2)
print("a:\n",a,"\n",a.shape)
print("b:\n",b,"\n",b.shape)
print("c:\n",c,"\n",c.shape)

a:
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 
 torch.Size([2, 3, 2])
b:
 tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 
 torch.Size([2, 3, 2])
c:
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 
 torch.Size([2, 3, 4])


In [ ]:
from typing import List
from collections import Counter

class Solution:
    def mostCommonWord(self, paragraph: str, banned: List[str]) -> str:
        # ban = set(banned)   set是不可变量
        freq = Counter()
        word, n = "", len(paragraph)
        for i in range(n + 1):
            # print(i)
            if i < n and paragraph[i].isalpha():
                word += paragraph[i].lower()
            elif word:
                if word not in banned:
                    freq[word] += 1
                word = ""
        maxFreq = max(freq.values())
        print(freq.items())
        return next(word for word, f in freq.items() if f == maxFreq)

paragraph = "Bob hit a ball, the hit BALL flew far after it was hit."
banned = ["hit"]


print(len(paragraph))
# print(paragraph[54])
Solution().mostCommonWord(paragraph, banned)

55
dict_items([('bob', 1), ('a', 1), ('ball', 2), ('the', 1), ('flew', 1), ('far', 1), ('after', 1), ('it', 1), ('was', 1)])


'ball'

In [ ]:
class Solution:
    def mostCommonWord(self, paragraph: str, banned: List[str]) -> str:
        ban = set(banned)
        freq = Counter()
        word, n = "", len(paragraph)
        for i in range(n):
            if paragraph[i].isalpha():
                word += paragraph[i].lower()
            elif word:        #### 因为此块判断是否禁用字的时候独立于上句if，所以会漏掉最后一个字的判定，所以错
                if word not in ban:
                    freq[word] += 1
                word = ""
        print(freq)
        max_freq = max(freq.values())
        return next(word for word, f in freq.items() if f == max_freq)

p="abd def d d d g g g"
Solution().mostCommonWord(p,b)

Counter({'d': 3, 'g': 2, 'abd': 1, 'def': 1})


'd'